export const permissionPresets: Record<string, string[]> = {
  core_team: [
    '/',
    '/tasks',
    '/projects',
    '/customers',
    '/calendar',
    '/my-work',
    '/notifications',
    '/wiki',
  ],
  manager: [
    '/',
    '/tasks',
    '/projects',
    '/customers',
    '/calendar',
    '/my-work',
    '/notifications',
    '/wiki',
    '/team',
    '/workload',
    '/reports',
    '/dashboard',
    '/okrs',
    '/leave',
    '/meetings',
    '/onsite-work',
    '/kpi',
  ],
  finance: [
    '/',
    '/budget',
    '/reports',
    '/customers',
    '/projects',
    '/export',
    '/my-work',
  ],
  viewer: [
    '/',
    '/dashboard',
    '/projects',
    '/customers',
    '/wiki',
  ],
  intern: [
    '/',
    '/my-work',
    '/tasks',
    '/calendar',
  ],
};

export type PresetKey = keyof typeof permissionPresets;
